name: quote_app
description: A Flutter application that show special quotes to user.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  http: ^0.11.3+16

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
